services:
  backend:
    build: "./backend"
    ports: ["8001:8001"]
    depends_on: ["cognito"]
  frontend:
    build: "./frontend"
    ports: ["8002:8002"]
    depends_on: ["backend", "cognito"]
  cognito:
    image: "jagregory/cognito-local:3-latest"
    ports: ["8003:8003"]
    environment: ["PORT=8003"]
