services:
  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile.dev"
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://postgres:pass@database:5432/postgres"
      COGNITO_POOL_ID: "$COGNITO_POOL_ID"
      COGNITO_CLIENT_ID: "$COGNITO_CLIENT_ID"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8001/api/v1/health"]
      interval: 1s
      timeout: 5s
      retries: 10
    depends_on:
      database:
        condition: "service_healthy"
  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile.dev"
    ports:
      - "8002:8002"
    environment:
      VITE_BACKEND_IP: "http://localhost:8001"
      VITE_COGNITO_CLIENT_ID: "$COGNITO_CLIENT_ID"
    depends_on:
      backend:
        condition: "service_healthy"
  database:
    image: "postgres:17.0-alpine"
    environment:
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ".postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
