services:
  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile.dev"
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://postgres:pass@database:5432/postgres"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8001/api/v1/health"]
      interval: 1s
      timeout: 5s
      retries: 10
    depends_on:
      cognito:
        condition: "service_started"
      database:
        condition: "service_healthy"
  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile.dev"
    ports:
      - "8002:8002"
    depends_on:
      cognito:
        condition: "service_started"
      backend:
        condition: "service_healthy"
  cognito:
    image: "jagregory/cognito-local:3-latest"
    ports:
      - "8003:9229"
  database:
    image: "postgres:17.0-alpine"
    ports:
      - "8004:5432"
    environment:
      POSTGRES_PASSWORD: "pass"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
